--SELECT * FROM LG_002_CLCARD
SELECT
O.CODE AS[Cari kodu],
L.DEFINITION_ AS[Cari adý],
I.ACCEPTEINV AS[E-FATURA MÜKELLEFÝ]

FROM LG_002_CLCARD TYP
LEFT JOIN LG_002_CLCARD O ON O.CODE=O.CODE
LEFT JOIN LG_002_CLCARD L ON L.DEFINITION_=L.DEFINITION_
LEFT JOIN LG_002_CLCARD I ON I.ACCEPTEINV=I.ACCEPTEINV  

WHERE O.CODE='0000000000000001' AND L.DEFINITION_='FATURA ÝÇÝ'


 --ACCEPTEINV