DECLARE @LOGICALREF INT
DECLARE @GLOBLINENO INT
DECLARE @MONTH INT
DECLARE @YEAR INT
------------------------------------
SET @GLOBLINENO=0
SET @MONTH=6     --- Bu alana ay bilgisi _017_
SET @YEAR=2016   --- Bu alana yýl bilgisi _017_
------------------------------------
DECLARE GLOBLINENO_NUMBER CURSOR FOR 
------------------------------------
SELECT 
                EM.LOGICALREF
FROM 
                LG_017_01_EMFICHE EF WITH(NOLOCK)
                LEFT OUTER JOIN LG_017_01_EMFLINE EM WITH(NOLOCK) ON EM.ACCFICHEREF=EF.LOGICALREF 
WHERE 
                EF.CANCELLED=0 AND (NOT (EF.TRCODE IN (5, 8, 10))) AND (EF.JOURNALNO > 0) AND (EF.STATUS = 0)  
                AND YEAR(EF.DATE_)=@YEAR AND MONTH(EF.DATE_)=@MONTH
                --  EF.BRANCH IN (0,3,4)  -- Ýþyerleri 
ORDER BY  
                           EF.JOURNALNO,EM.LINENO_  
------------------------------------   
OPEN GLOBLINENO_NUMBER
FETCH NEXT FROM GLOBLINENO_NUMBER  INTO @LOGICALREF
WHILE @@FETCH_STATUS = 0
BEGIN
SET ROWCOUNT 0
------------------------------------
IF @GLOBLINENO=0
BEGIN
SELECT @GLOBLINENO=ISNULL(MAX(GLOBLINENO),0) FROM LG_017_01_EMFLINE WHERE MONTH(DATE_)=@MONTH-1
END
UPDATE LG_017_01_EMFLINE SET GLOBLINENO=@GLOBLINENO+1 WHERE LOGICALREF = @LOGICALREF

SELECT @GLOBLINENO=@GLOBLINENO+1
------------------------------------       
FETCH NEXT FROM GLOBLINENO_NUMBER
INTO @LOGICALREF
END
CLOSE GLOBLINENO_NUMBER
DEALLOCATE GLOBLINENO_NUMBER
------------------------------------


