	--SELECT ORDFICHEREF,*FROM LG_001_01_STLINE
	--select SHIPPED,* from LG_001_01_ORFICHE
	--SELECT SHIPPED,* FROM LG_001_01_STFICHE
	--SELECT * FROM LG_001_01_ORFLINE
	--SELECT SHIPPED,* FROM LG_001_ITEMS
	--SELECT AMOUNT,* FROM LG_001_01_ORFLINE
	--SELECT * FROM LG_001_01_ORFICHE
	--SELECT SHIPPED,* FROM LG_001_01_ORFLINE
	--SELECT * FROM LG_001_01_STINVTOT
	--SELECT SHIPPED* FROM LG_001_01_ORFLINE
	-----------------------------------------------------------------------------------------
	--SIPARIS NUMARASI
	--IRSALIYE NUMARASI
	--MALZEME ADI
	--MALZEME KODU		
	--SIPARISIN MIKTARI
	--IRSALIYE MIKTARI
	--FATURA NUMARASI
	--FATURA TARIHI
	--SEVKEDÝLEN MIKTAR
	--BEKLEYEN MIKTAR

	---------------------------------------------------------------------------------------------------

SELECT
ORF.FICHENO [SÝPARÝÞ FÝÞ NO],
STF.FICHENO [IRSALIYE NO],
IT.CODE[MALZEME KODU],
IT.NAME[MALZEME ADI],
ORL.AMOUNT[SÝPARÝÞ MÝKTARI],
ORL.SHIPPEDAMOUNT[ÝRSALÝYE MÝKTARI],
INV.FICHENO[FATURA NO],
INV.DATE_[FATURA TARÝHÝ],
ORL.SHIPPEDAMOUNT[SEVKEDÝLEN MÝKTAR],
(ORL.AMOUNT-ORL.SHIPPEDAMOUNT) [BEKLEYEN MÝKTAR]

FROM LG_001_01_STLINE STL


LEFT JOIN LG_001_01_ORFICHE ORF ON STL.ORDFICHEREF=ORF.LOGICALREF
LEFT JOIN LG_001_01_STFICHE STF ON STL.STFICHEREF=STF.LOGICALREF    
LEFT JOIN LG_001_ITEMS IT ON STL.STOCKREF=IT.LOGICALREF
LEFT JOIN LG_001_01_ORFLINE ORL ON ORF.LOGICALREF=ORL.ORDFICHEREF
LEFT JOIN LG_001_01_INVOICE INV ON STL.INVOICEREF=INV.LOGICALREF




--WHERE  