

--SELECT * FROM LG_009_01_STLINE
--SELECT * FROM LG_009_ITEMS
--LG_009_01_STFICHE
--SELECT * FROM LG_009_01_INVOICE
--SELECT * FROM LG_009_CLCARD


SELECT
INV.FICHENO [FATURA NO]
,INV.DATE_ [FATURA TARÝHÝ]
,CLCARD.CODE AS CARÝ_KODU
,CLCARD.DEFINITION_  'CARÝ KODU'
,CLCARD.CODE +' '+ CLCARD.DEFINITION_ AS AÇIKLAMASI
,MONTH(INV.DATE_) 'FATURA AYI'
,STF.FICHENO 'ÝRSALÝYE NO'
,STF.DATE_ AS FÝÞ_TARÝHÝ
,IT.CODE AS STOK_KODU
,IT.NAME AS STOK_ADI
,STLINE.AMOUNT AS MÝKTAR
,STLINE.VATMATRAH AS KDV_MATRAHI
,STLINE.VATAMNT AS KDV_TUTARI
,(STLINE.VATMATRAH+STLINE.VATAMNT) AS NET_TUTAR


FROM LG_009_01_STLINE  STLINE
LEFT JOIN LG_009_01_STFICHE STF ON STLINE.STFICHEREF=STF.LOGICALREF
LEFT JOIN LG_009_01_INVOICE INV ON STLINE.INVOICEREF=INV.LOGICALREF
LEFT JOIN LG_009_ITEMS IT ON STLINE.STOCKREF=IT.LOGICALREF
LEFT JOIN LG_009_CLCARD CLCARD ON STLINE.CLIENTREF=CLCARD.LOGICALREF

WHERE STLINE.TRCODE IN (8) AND STLINE.LINETYPE IN (0)
